### ISSUE TITLE
Greetings to the author from the first likely user.

### ISSUE THREAD

**Issue by christianwol-ff** [AnderHominem/PC-time-counter#1]
I congratulate you, author, and thank you for your simple and realistic programmes that are relevant to today's problems. Yes, yes, in the plural, because I believe in the progress of your work.

The essence of my proposal is to add your program to Scoop, if possible.

This will increase the audience by an order of magnitude and will make you as an author of interest to the widest possible audience.

Including me.

**Comment by AnderHominem** [comment]
This might be a very good proposal, but there is one problem, I don't know what Scoop is, yet :D

**Comment by AnderHominem** [comment]
I asked the GPT what this is, and yes, it's a really good idea, I don't know how to do it, yet, but I think it will be a good opportunity to practice

**Comment by AnderHominem** [comment]
I did it, now the program has installer
